name: Build OSS Kernel for Redmi Note 9 Pro (Curtana) with Proton Clang

on:
  workflow_dispatch:

# Add permissions for artifact upload
permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the kernel source
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: MiCode/Xiaomi_Kernel_OpenSource
          ref: curtana-q-oss
          fetch-depth: 1

      # Debug step to check if runner picks up
      - name: Debug Runner
        run: echo "Runner is working! This is ubuntu-latest."

      # Set up ccache to speed up compilation
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 5G

      # Clone Proton Clang
      - name: Clone Proton Clang
        run: |
          git clone --depth=1 --branch master https://github.com/kdrag0n/proton-clang.git proton-clang
          echo "PROTON_CLANG_DIR=$(pwd)/proton-clang" >> $GITHUB_ENV

      # Install basic dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bc bash coreutils diffutils findutils \
            make python3 flex bison libssl-dev libncurses5-dev libncursesw5-dev zip

      # Set up environment variables for Proton Clang
      - name: Set Environment Variables
        run: |
          echo "PATH=${{ env.PROTON_CLANG_DIR }}/bin:$PATH" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabihf-" >> $GITHUB_ENV  # For 32-bit vDSO if needed
          echo "KBUILD_BUILD_USER=MINHAZ" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=POTATO" >> $GITHUB_ENV

      # Create out directory if it doesn't exist
      - name: Create Output Directory
        run: |
          if [ ! -d "out" ]; then
            mkdir out
          fi

      # Compile defconfig
      - name: Generate Defconfig
        run: |
          make O=out vendor/atoll-perf_defconfig

      # Compile kernel
      - name: Compile Kernel
        run: |
          make -j$(nproc) O=out CC="${CC}" CXX="${CXX}" \
            ARCH=${ARCH} SUBARCH=${SUBARCH} \
            CROSS_COMPILE=${CROSS_COMPILE} \
            CROSS_COMPILE_COMPAT=${CROSS_COMPILE_COMPAT} \
            2>&1 | tee kernel.log

      # Compile and install modules
      - name: Compile and Install Modules
        run: |
          make -j$(nproc) O=out CC="${CC}" CXX="${CXX}" \
            ARCH=${ARCH} SUBARCH=${SUBARCH} \
            CROSS_COMPILE=${CROSS_COMPILE} \
            CROSS_COMPILE_COMPAT=${CROSS_COMPILE_COMPAT} \
            INSTALL_MOD_PATH=out modules_install

      # Checkout AnyKernel3
      - name: Checkout AnyKernel3
        uses: actions/checkout@v4
        with:
          repository: ImONE-Na/AnyKernel3
          ref: master
          path: AnyKernel3

      # Customize AnyKernel3
      - name: Customize AnyKernel3
        run: |
          sed -i 's/kernel.compiler=.*/kernel.compiler=Proton Clang/' AnyKernel3/anykernel.sh
          sed -i 's/kernel.version=.*/kernel.version=4.14.117/' AnyKernel3/anykernel.sh

      # Copy kernel image, dtb, dtbo, and modules to AnyKernel3
      - name: Copy Files to AnyKernel3
        run: |
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/ || true
          cp out/arch/arm64/boot/dtb.img AnyKernel3/ || true
          mkdir -p AnyKernel3/modules
          find out/lib/modules -type f -name "*.ko" -exec cp {} AnyKernel3/modules/ \;

      # Create flashable zip
      - name: Create Flashable Zip
        working-directory: AnyKernel3
        run: |
          zip -r9 ../OSS-Kernel-Curtana.zip * -x .git README.md *placeholder

      # Upload artifact
      - name: Upload Flashable Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSS-Kernel-Curtana
          path: OSS-Kernel-Curtana.zip
          retention-days: 7
